import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'
import Router from 'next/router'
import { auth, logOut } from "../firebase/clientApp"
import { useAuthState } from "react-firebase-hooks/auth"
import { Button } from 'react-bootstrap'

const Home: NextPage = () => {
  const [user, loading, error] = useAuthState(auth)

  useEffect(() => {
    user || Router.push("/login")
  })

  const handleClick = async () => {
    await logOut()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1>Hello {user && user.email}</h1>
        <Button onClick={handleClick}>Logout</Button>
      </section>
    </div>
  )
}

export default Home